In [1]:
import numpy as np

In [2]:
a=np.array([1,2,3])

In [3]:
a

array([1, 2, 3])

In [4]:
print(a)

[1 2 3]


In [5]:
a=np.array([(1,2,3),(4,5,6)])

In [6]:
print(a)

[[1 2 3]
 [4 5 6]]


In [7]:
import sys

L=range(10000)
print(sys.getsizeof(5)*len(L))

280000


In [15]:
A=np.arange(10000,dtype='int8')
print(A.itemsize * A.size)

10000


In [9]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
a.itemsize

4

In [11]:
a.size

6

In [12]:
a.ndim

2

In [13]:
a.dtype

dtype('int32')

In [22]:
import time

SIZE=100000
L1=range(SIZE)
L2=range(SIZE)

A1=np.arange(SIZE)
A2=np.arange(SIZE)

start=time.time()
result=[x+y for x,y in zip(L1,L2)]
end=time.time()
print((end-start)*1000)



10.142087936401367


In [23]:
start=time.time()
res=A1+A2
end=time.time()
print((end-start)*1000)

0.0


In [24]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [25]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [26]:
a.shape

(3, 3)

In [27]:
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
a[1,1]

5

In [29]:
a[1:,1:]

array([[5, 6],
       [8, 9]])

In [30]:
a[:,2]

array([3, 6, 9])

In [31]:
a=np.array([(1,2,3,4),(3,4,5,6),(7,8,9,10)])

In [32]:
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [33]:
a.shape

(3, 4)

In [34]:
a.reshape(4,3)

array([[ 1,  2,  3],
       [ 4,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [35]:
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [36]:
a[0:2,3]

array([4, 6])

In [37]:
a.min()

1

In [38]:
a.max()

10

In [39]:
a.sum()

62

In [40]:
a

array([[ 1,  2,  3,  4],
       [ 3,  4,  5,  6],
       [ 7,  8,  9, 10]])

In [41]:
a.sum(axis=0)

array([11, 14, 17, 20])

In [42]:
a.sum(axis=1)

array([10, 18, 34])

In [43]:
np.sqrt(a)

array([[1.        , 1.41421356, 1.73205081, 2.        ],
       [1.73205081, 2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        , 3.16227766]])

In [44]:
np.std(a)

2.733536577809454

In [54]:
a=np.array([(1,2,3),(4,5,6)])
b=np.array([(1,2,3),(4,5,6)])

In [46]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [47]:
a+b

array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [48]:
a-b

array([[0, 0, 0],
       [0, 0, 0]])

In [49]:
a*b

array([[ 1,  4,  9],
       [16, 25, 36]])

In [55]:
np.dot(a,b)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [56]:
a=np.array([(1,2,3),(4,5,6),(7,8,9)])
b=np.array([(1,2,3),(4,5,6),(7,8,9)])

In [59]:
np.dot(a,b)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [61]:
np.hstack((a,b))

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6],
       [7, 8, 9, 7, 8, 9]])

In [62]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [63]:
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [64]:
a.ravel()

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.log(a)

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947],
       [1.94591015, 2.07944154, 2.19722458]])

In [66]:
np.exp(a)

array([[2.71828183e+00, 7.38905610e+00, 2.00855369e+01],
       [5.45981500e+01, 1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03, 8.10308393e+03]])

In [68]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [69]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [70]:
np.full((3,3),99)

array([[99, 99, 99],
       [99, 99, 99],
       [99, 99, 99]])

In [71]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])